website/views/auth.py
# Manual imports
from website.models.forms import RegisterUserForm, RegisterDoctorForm, LoginForm
from website.models.tables import User, Doctor
from website.views.app import login_manager, db

# Flask imports
from flask import Blueprint, render_template, redirect, url_for, request, flash, session

# Form imports
from wtforms import *
from wtforms.validators import *

# Database imports
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)

@auth.route('/signup/')
def sign_up():
    return redirect(url_for('auth.sign_up_as_user'))


@auth.route('/signup/user/', methods=["POST", "GET"])
def sign_up_as_user():
    form = RegisterUserForm()

    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, method='sha256')
        
        # Count no of rows (users) to get current ID
        total_id = User.query.filter(User.id > 0).count()
        
        id = total_id + 1
        firstname = form.firstname.data.lower().capitalize()
        lastname = form.lastname.data.lower().capitalize()
        username = form.username.data.lower()
        email = form.email.data.lower()
        password = hashed_password
        gender = form.gender.data.lower().capitalize()
        blood_group = form.blood_group.data.capitalize()
        height_ft = form.height_ft.data
        height_inch = form.height_inch.data
        weight_kg = form.weight_kg.data
        phone = form.phone.data
        zipcode = form.zipcode.data
        city = form.city.data.lower().capitalize()
        state = form.state.data.lower().capitalize()

        new_user = User(id, firstname, lastname, username, email, password, gender, blood_group, height_ft, height_inch, weight_kg, phone, zipcode, city, state)
        
        status = ""

        try:
            db.session.add(new_user)
            status = "success"
        except:
            db.session.rollback()
            status = "error"
        finally:
            db.session.commit()

            if status == "success":
                flash("Successfully Signed up", "success")
                return redirect(url_for('auth.log_in'))
            else:
                flash("Signing up failed", "error")
                return render_template("pages/auth/signupUser.html", form=form)
    else:
        return render_template("pages/auth/signupUser.html", form=form)   
        

@auth.route('/signup/doctor/', methods=["POST", "GET"])
def sign_up_as_doctor():
    form = RegisterDoctorForm()

    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, method='sha256')
        
        # Count no of rows (doctors) to get current ID
        total_id = Doctor.query.filter(Doctor.id > 0).count()
        
        id = total_id + 1
        firstname = form.firstname.data.lower().capitalize()
        lastname = form.lastname.data.lower().capitalize()
        username = form.username.data.lower()
        email = form.email.data.lower()
        password = hashed_password
        gender = form.gender.data.lower().capitalize()
        blood_group = form.blood_group.data.capitalize()
        height_ft = form.height_ft.data
        height_inch = form.height_inch.data
        weight_kg = form.weight_kg.data
        type = form.type.data.lower().capitalize()
        phone = form.phone.data
        zipcode = form.zipcode.data
        city = form.city.data.lower().capitalize()
        state = form.state.data.lower().capitalize()

        new_doctor = Doctor(id, firstname, lastname, username, email, password, gender, blood_group, height_ft, height_inch, weight_kg, type, phone, zipcode, city, state)

        status = ""

        try:
            db.session.add(new_doctor)
            status = "success"
        except:
            db.session.rollback()
            status = "error"
        finally:
            db.session.commit()

            if status == "success":
                flash("Successfully Signed up", "success")
                return redirect(url_for('auth.log_in'))
            else:
                flash("Signing up failed", "error")
                return render_template("pages/auth/signupDoctor.html", form=form)
    else:
        return render_template("pages/auth/signupDoctor.html", form=form)   
  

@auth.route("/login/", methods=["POST", "GET"])
def log_in():
    form = LoginForm()

    if form.validate_on_submit():
        next_url = request.form.get("next")

        for i in ['user', 'doctor']:
            for j in ['username', 'email']:
                try:
                    if i == 'user':
                        if j == 'username':
                            person = User.query.filter_by(username=form.username.data.lower()).first()
                        elif j == 'email':
                            person = User.query.filter_by(email=form.username.data.lower()).first()
                        
                    elif i == 'doctor':
                        if j == 'username':
                            person = Doctor.query.filter_by(username=form.username.data.lower()).first()
                        elif j == 'email':
                            person = Doctor.query.filter_by(email=form.username.data.lower()).first()
                        
                    if check_password_hash(person.password, form.password.data):
                        login_user(person, remember=form.remember.data)
                        db.session.commit()

                        session["id"] = str(current_user.id)
                        session["username"] = str(current_user.username)

                        if next_url:
                            flash("Successfully Logged in ", "success")
                            return redirect(next_url)
                        else:
                            flash("Successfully Logged in ", "success")
                            return redirect(url_for('home.homepage'))
                    else:
                        flash("The username or password is incorrect", "error")
                        return render_template("pages/auth/login.html", form=form)
                except:
                    pass
        flash("This Username or Email ID doesn't exist", "error")

    return render_template("pages/auth/login.html", form=form)
    

@auth.route("/logout/")
@login_required
def log_out():
    db.session.commit()
    logout_user()

    session["id"] = None
    session["username"] = None

    flash("Successfully Logged out", "success")
    return redirect(url_for('home.homepage'))


@login_manager.user_loader
def load_user(username):
    person = User.query.filter_by(username=username).first()

    # checking does given username/email exist in User table
    if person is not None: 
        return ( User.query.get(person.id) )
    # checking does given username/email exist in Doctor table
    else:
        person = Doctor.query.filter_by(username=username).first()
        return ( Doctor.query.get(person.id) )
    # pass

website/views/blog.py
from flask import Blueprint, render_template


blog = Blueprint('blog', __name__)

@blog.route("/")
def home():
    return render_template("pages/blog/blog.html")

website/views/chat.py
from flask import Blueprint, render_template

chat = Blueprint('chat', __name__)

@chat.route("/")
def home():
    return render_template("pages/chat/chat.html")

website/views/shop.py
from flask import Blueprint, render_template


shop = Blueprint('shop', __name__)

@shop.route("/")
def home():
    return render_template("pages/shop/shop.html")

website/templates/macros/macro.html
{% macro links() %}
<head>
    <!-- Meta Tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv='cache-control' content='no-cache'>
    <meta http-equiv='expires' content='0'>
    <meta http-equiv='pragma' content='no-cache'>
    <meta name="description" content="CRM for Doctors - Find and book an appointment with your nearest doctor.">
    <meta name="application-name" content="CRM for Doctors">
    <meta name="theme-color" content="#256679">
    
    <!-- JQuery -->
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    <!-- GSAP -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.6.0/gsap.min.js" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.7.0/gsap.min.js" integrity="sha512-2fk3Q4NXPYAqIha0glLZ2nluueK43aNoxvijPf53+DgL7UW9mkN+uXc1aEmnZdkkZVvtJZltpRt+JqTWc3TS3Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    <!-- Google APIs -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href = "https://fonts.googleapis.com/icon?family=Material+Icons" rel = "stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Baloo+Bhai+2:wght@400;500;600;700;800&display=swap">
    
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
{% endmacro %}


{% macro dummyNav() %}
<div class="dummyNav"></div>
{% endmacro %}


{% macro nav(chat_class) %}
<nav>
    <i class="fa fa-bars"></i>
    <i class="fa fa-times"></i>
    <h1 id="title"> Secret Web App</h1>
    <a class="{{chat_class}}" id="chat" href="{{ url_for('chat.home') }}"><i class="fa fa-comment"></i></a>
</nav>
{% endmacro %}


{% macro sidePanel(current_user) %}
<div class="sidePanel" id="sidePanel">
    <ul>
        <li class="sidePanel-item">
            <i class="fa fa-pencil"></i>
            <a class="nav-link" href="{{ url_for('blog.home') }}"><p>Blog</p></a>
        </li>

        <li class="sidePanel-item">
            <i class="fa fa-info"></i>
            <a class="nav-link" href="#"><p>About Us</p></a>
        </li>

        <li class="sidePanel-item">
            <i class="fa fa-user-secret"></i>
            <a class="nav-link" href="#"><p>Privacy Policy</p></a>
        </li>

        <li class="sidePanel-item">
            <i class="fa fa-key"></i>
            <a class="nav-link" href="#"><p>Terms & Conditions</p></a>
        </li>

        <hr class="sidePanel-item">
        
        {% if current_user.is_authenticated == False %}
            <li class="sidePanel-item highlight">
                <i class="fa fa-user-plus"></i>
                <a class="nav-link" href="{{ url_for('auth.sign_up') }}"><p>Sign up</p></a>
            </li>
            
            <li class="sidePanel-item highlight">
                <i class="fa fa-sign-out"></i>
                <a class="nav-link" href="{{ url_for('auth.log_in') }}"><p>Log in</p></a>
            </li>
        {% else %}   
            <li class="sidePanel-item highlight-alert">
                <i class="fa fa-sign-out"></i>
                <a class="nav-link" href="{{ url_for('auth.log_out') }}"><p>Log out</p></a>
            </li>
        {% endif %}
    </ul>
</div>
{% endmacro %}


{% macro footer(shop,home,user) %}
<footer>
    <a class="{{shop}}" id="shop" href="{{ url_for('shop.home') }}"><i class="fa fa-shopping-cart"></i></a>
    <a class="{{home}}" id="home" href="{{ url_for('home.homepage') }}"><i class="fa fa-home"></i></a>
    <a class="{{user}}" id="user" href="{{ url_for('user.home') }}"><i class="fa fa-user"></i></a>
</footer>
{% endmacro %}