website/views/doctors.py
# Inbuilt imports
import calendar, datetime, math

# External imports
from pytz import *

# Flask imports
from flask import Blueprint, render_template, session, redirect

# Manual imports
from website.models.tables import Doctor, User
from website.models.forms import Appointment

# Database imports
from flask_login import login_required


doctors = Blueprint('doctors', __name__)


# For doctor profile ------------------------------------------------------------------------------

@doctors.route('/categories/<doctor_type>/')
def doctor_profile_by_type(doctor_type):
    doctors = Doctor.query.filter_by(type=doctor_type.capitalize()).all()

    message = "No doctors found for " + doctor_type + " !"
    if doctor_type == "radiologist":
        message = "No " + doctor_type + " found !"

    if doctors:
        return render_template("pages/home.html", doctors=doctors)
    else:
        return render_template("pages/home.html", message=message)


@doctors.route('/<doctor_id>/')
def doctor_profile(doctor_id):
    doctors = Doctor.query.filter_by(id=doctor_id).first()

    if doctors:
        return render_template("pages/doctor/doctorProfile.html", doctors=doctors)
    else:
        return "<h1>Doctor not found !!!</h1>"


# For appointments --------------------------------------------------------------------------------

@doctors.route('/<doctor_id>/appointment/booking/')
@login_required
def doctor_appointment(doctor_id):
    form = Appointment()
    
    # Current time in UTC
    today_utc = datetime.datetime.now(timezone('UTC'))
    
    # Convert to Asia/Kolkata time zone
    today_india = today_utc.astimezone(timezone('Asia/Kolkata'))

    # Date variables
    date         =  int(today_india.strftime("%d"))     # 7
    hour         =  int(today_india.strftime("%I"))     # 07
    minute       =  int(today_india.strftime("%M"))     # 7
    meridiem     =  today_india.strftime("%p")          # AM
    weekday      =  today_india.strftime("%a")          # SUN
    weekday_int  =  today_india.strftime("%u")          # 1
    month        =  today_india.strftime("%b")          # APR
    month_int    =  today_india.strftime("%m")          # 4
    year_full    =  today_india.strftime("%Y")          # 2021
    year_short   =  today_india.strftime("%y")          # 21

    dates = []
    slots = {}
    no_of_days = 3     # Number of days to take appointment in future

    for i in range(0, no_of_days):
        loop_date = today_india + datetime.timedelta(days=i)
        date = {}
        date["weekday"] = loop_date.strftime("%a")
        date["date"] = loop_date.strftime("%d")
        date["month"] = loop_date.strftime("%b")
        date["month_int"] = loop_date.strftime("%m")
        date["year_full"] = loop_date.strftime("%Y")

        dates.append(date)

    # Above loop is used to create alike this list of future days for appointment
    # dates = [   {'weekday': 'Tue', 'date': '12', 'month': 'Mar', 'month_int': 3, 'year_full': 2021},
    #             {'weekday': 'Wed', 'date': '13', 'month': 'Mar', 'month_int': 3, 'year_full': 2021}
    #         ]
    
    for i in range(0, no_of_days):
        loop_date = today_india + datetime.timedelta(days=i)
        slot = {}
        slot["hour"] = loop_date.strftime("%a")
        slot["minute"] = loop_date.strftime("%a")
        slot["meridiem"] = loop_date.strftime("%a")
        slot["date"] = loop_date.strftime("%d")
        slot["month_int"] = loop_date.strftime("%m")
        slot["year_full"] = loop_date.strftime("%Y")

        # slots.append(date)
    # get json list of all slots from database column and using loop print all available slots
    # 
    # slots = {  "date-month_int-year_full": [ ['hour', 'minute', 'meridiem'],
    #                                          ['hour', 'minute', 'meridiem']
    #                                        ],
    # 
    #            "13-10-2021": [ ['12', 3, 'AM'],
    #                            ['12', 3, 'PM']
    #                          ]
    #         }
    
    return render_template("pages/doctor/doctorAppointment.html", form=form, dates=dates, _doctor_id=doctor_id)


@doctors.route('/<doctor_id>/appointment/confirmation/')
def doctor_appointment_confirmation(doctor_id):
    form = ""
    return render_template("pages/doctor/appointmentConfirmation.html", form=form)


# For ratings -------------------------------------------------------------------------------------

def round_up(n, decimals=0):
    multiplier = 10 ** decimals
    return math.ceil(n * multiplier) / multiplier

def fetch_rating():
    _5_stars_count = 252
    _4_stars_count = 124
    _3_stars_count = 40
    _2_stars_count = 29
    _1_stars_count = 33

    _5_stars_sum = 5 * _5_stars_count
    _4_stars_sum = 4 * _4_stars_count
    _3_stars_sum = 3 * _3_stars_count
    _2_stars_sum = 2 * _2_stars_count
    _1_stars_sum = 1 * _1_stars_count

    total_rating = _5_stars_sum + _4_stars_sum + _3_stars_sum + _2_stars_sum + _1_stars_sum
    total_count = _5_stars_count + _4_stars_count + _3_stars_count + _2_stars_count + _1_stars_count
    
    overall_rating = round_up( (total_rating / total_count), decimals=3 )

website/templates/pages/doctor/appointmentConfirmation.html
{% from "/macros/macro.html" import links, dummyNav, nav, sidePanel, footer %}

<!DOCTYPE html>
<html lang="en" data-theme="dark">
    <head>
        {{ links()}}

        <link rel="stylesheet" href="{{url_for('static', filename='css/nfs.css')}}">
        <link rel="stylesheet" href="{{url_for('static', filename='css/home.css')}}">
        <link rel="stylesheet" href="{{url_for('static', filename='css/essentials.css')}}">
        <link rel="stylesheet" href="{{url_for('static', filename='css/login.css')}}">
        <link rel="stylesheet" media="screen and (max-width: 576px)" href="{{url_for('static', filename='css/mobile/login.css')}}">
        
        <title>Login</title>

        <style>
            
        </style>
    </head>

<body>
    <header>
        {{ dummyNav() }}
        {{ nav() }}
        {{ sidePanel(current_user) }}
        
        {% with success = get_flashed_messages(category_filter=["success"]) %}
            {% if success %}
                <div class="flash" id="flash-success">
                    <ul>
                        {% for msg in success %}
                            <li class="flash-message" data-type="success"><i class="fa fa-exclamation-triangle"></i>{{ msg }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        {% endwith %}

        {% with errors = get_flashed_messages(category_filter=["error"]) %}
            {% if errors %}
                <div class="flash" id="flash-error">
                    <ul>
                        {% for msg in errors %}
                            <li class="error-message" data-type="error"><i class="fa fa-exclamation-triangle"></i>{{ msg }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        {% endwith %}
    </header>
    
    <main>
        <section class="content">
            <div class="container">
            </div>
        </section>
    </main>
    
    {{ dummyNav() }}
    {{ footer("footer-item", "footer-item", "footer-item") }}

    <script type = "text/javascript" src = "{{ url_for('static', filename = 'js/essentials.js') }}"></script>
    <script type = "text/javascript" src = "{{ url_for('static', filename = 'js/nav.js') }}"></script>
</body>
</html>

website/templates/pages/doctor/doctorAppointment.html
{% from "/macros/macro.html" import links, dummyNav, nav, sidePanel, footer %}

<!DOCTYPE html>
<html lang="en" data-theme="dark">
    <head>
        {{ links()}}

        <link rel="stylesheet" href="{{url_for('static', filename='css/nfs.css')}}">
        <link rel="stylesheet" href="{{url_for('static', filename='css/home.css')}}">
        <link rel="stylesheet" href="{{url_for('static', filename='css/essentials.css')}}">
        <link rel="stylesheet" href="{{url_for('static', filename='css/components/doctor/doctorAppointment.css')}}">
        <link rel="stylesheet" media="screen and (max-width: 576px)" href="{{url_for('static', filename='css/mobile/doctorAppointment.css')}}">
        
        <title>Login</title>

        <style>
            
        </style>
    </head>

<body>
    <header>
        {{ dummyNav() }}
        {{ nav() }}
        {{ sidePanel(current_user) }}
        
        {% with success = get_flashed_messages(category_filter=["success"]) %}
            {% if success %}
                <div class="flash" id="flash-success">
                    <ul>
                        {% for msg in success %}
                            <li class="flash-message" data-type="success"><i class="fa fa-exclamation-triangle"></i>{{ msg }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        {% endwith %}

        {% with errors = get_flashed_messages(category_filter=["error"]) %}
            {% if errors %}
                <div class="flash" id="flash-error">
                    <ul>
                        {% for msg in errors %}
                            <li class="error-message" data-type="error"><i class="fa fa-exclamation-triangle"></i>{{ msg }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        {% endwith %}
    </header>
    
    <main>
        <section class="content">
            <div class="container">
                <!-- Dates -->
                <section class="section" style="margin-top: 25px;">
                    <h2>Select date to visit</h2>

                    <div class="date-div">
                        {% for date in dates %}
                            {% if dates.index(date) == 0 %}    
                                <div class="date selected" data-date='{{date["date"]}}-{{date["month_int"]}}-{{date["year_full"]}}'>{{date["weekday"]}}<br>{{date["date"]}}<br>{{date["month"]}}</div>
                            {% else %}
                                <div class="date" data-date='{{date["date"]}}-{{date["month_int"]}}-{{date["year_full"]}}'>{{date["weekday"]}}<br>{{date["date"]}}<br>{{date["month"]}}</div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </section>

                <!-- Slots -->
                <section class="section" style="margin-bottom: 30px;">
                    <h2>Slots available</h2>

                    <div class="time-div 20-10-2021">
                        <div class="time selected" data-time="08 : 00 AM"><span>08 : 00 AM</span></div>
                        <div class="time" data-time="08 : 30 AM"><span>08 : 30 AM</span></div>
                        <div class="time" data-time="09 : 00 AM"><span>09 : 00 AM</span></div>
                        <div class="time" data-time="02 : 30 PM"><span>02 : 30 PM</span></div>
                        <div class="time" data-time="08 : 30 PM"><span>08 : 30 PM</span></div>
                    </div>

                    <div class="time-div 21-10-2021">
                        <div class="time" data-time="08 : 00 AM"><span>08 : 00 AM</span></div>
                        <div class="time" data-time="08 : 30 AM"><span>08 : 30 AM</span></div>
                        <div class="time" data-time="09 : 00 AM"><span>09 : 00 AM</span></div>
                        <div class="time" data-time="09 : 30 AM"><span>09 : 30 AM</span></div>
                        <div class="time" data-time="10 : 00 AM"><span>10 : 00 AM</span></div>
                    </div>
                   
                    <div class="time-div 22-10-2021">
                        <div class="time" data-time="08 : 00 AM"><span>08 : 00 AM</span></div>
                        <div class="time" data-time="08 : 30 AM"><span>08 : 30 AM</span></div>
                        <div class="time" data-time="09 : 00 AM"><span>09 : 00 AM</span></div>
                        <div class="time" data-time="09 : 30 AM"><span>09 : 30 AM</span></div>
                        <div class="time" data-time="10 : 00 AM"><span>10 : 00 AM</span></div>
                    </div>
                </section>

                <!-- Button -->
                <section class="section">
                    <div class="button book">Book</div>
                </section>
            </div>
        </section>

        <!-- Overlay -->
        <div class="overlay">
            <div class="confirmation-div" style="display: block;">
                <!-- <i class="fa fa-times"></i> -->
                
                <form id="form" method="POST, GET" action="{{ url_for('doctors.doctor_appointment_confirmation', doctor_id=_doctor_id) }}">
                    <div>
                        {{ form.csrf_token }}
                    </div>

                    <div class="fields-div">
                        <div class="fields-sub-div">
                            <!-- Date -->
                            <div class="fields">
                                {{ form.date.label }}
                                {{ form.date(placeholder="Date : ", autocomplete="off", readonly=true) }}
                            </div>

                            <!-- Time -->
                            <div class="fields">
                                {{ form.time.label }}
                                {{ form.time(placeholder="Time : ", autocomplete="off", readonly=true) }}
                            </div>
                        </div>
                    </div>

                    <!-- Form buttons -->
                    <div class="bottom-buttons">
                        <div class="fields">
                            <input class="button edit" id="editButton" type="reset" value="Edit">
                            <input class="button" type="submit" value="Confirm">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </main>
    
    {{ dummyNav() }}
    {{ footer("footer-item", "footer-item", "footer-item") }}

    <script type = "text/javascript" src = "{{ url_for('static', filename = 'js/essentials.js') }}"></script>
    <script type = "text/javascript" src = "{{ url_for('static', filename = 'js/nav.js') }}"></script>

    <script>
        // Booking button functions
        $('.button.book').click(function(){
            // getDate
            var date_value = document.querySelector('.date.selected').getAttribute('data-date');
            document.getElementById("date").value = date_value;    

            // getTime
            var time_class = document.getElementsByClassName(date_value);

            if ( $('.' + date_value).find($('.time.selected')).length != 0){
                var time_value = time_class[0].querySelector('.time.selected').getAttribute('data-time');
                document.getElementById("time").value = time_value;

                // Open overlay
                $(".overlay").css("display", "block");
                $(".confirmation-div").css("display", "block");
                $("body").css("pointer-events", "none");
                    
                $('.button.edit').click(function(){ 
                    $(".filter").css("display", "none");
                    $("body").css("pointer-events", "all");
                    $(".overlay").css("display", "none");
                });
            }
            else{
                alert("PLEASE SELECT SLOT");
            }
        });
        
        // Filter slots
        $(document).ready(function (){
            $('.date').click(function () {
                const value = $(this).attr('data-date');
                var className = $(this).attr('class');

                $('.time-div').not('.' + value).hide('1000');
                $('.time-div').filter('.' + value).show('1000');
                
                //  Change class of selected date
                if (className != 'date selected'){
                    $(this).toggleClass('selected').siblings().removeClass('selected');
                }
                
                var time_class = document.getElementsByClassName(value);
                time_class[0].style.display = "flex";
            });

            // Change class of selected time
            $('.time').click(function () {
                $(this).toggleClass('selected').siblings().removeClass('selected');
            });
        });
    </script>
</body>
</html>

website/templates/pages/doctor/doctorProfile.html
{% from "/macros/macro.html" import links, dummyNav, nav, sidePanel, footer %}
{% from "/components/component.html" import doctorCard %}

<!DOCTYPE html>
<html lang="en" data-theme="dark">
    <head>
        {{ links()}}

        <link rel="stylesheet" href="{{url_for('static', filename='css/nfs.css')}}">
        <link rel="stylesheet" href="{{url_for('static', filename='css/home.css')}}">
        <link rel="stylesheet" href="{{url_for('static', filename='css/essentials.css')}}">
        <link rel="stylesheet" href="{{url_for('static', filename='css/doctorProfile.css')}}">
        <link rel="stylesheet" href="{{url_for('static', filename='css/components/doctor/doctor-card.css')}}">
        <link rel="stylesheet" media="screen and (max-width: 576px)" href="{{url_for('static', filename='css/mobile/doctorProfile.css')}}">
        <link rel="stylesheet" media="screen and (max-width: 576px)" href="{{url_for('static', filename='css/mobile/doctor-card.css')}}">
        
        <title>Doctor Profile</title>

        <style>
            
        </style>
    </head>

<body>
    <header>
        {{ dummyNav() }}
        {{ nav() }}
        {{ sidePanel(current_user) }}
        
        {% with success = get_flashed_messages(category_filter=["success"]) %}
            {% if success %}
                <div class="flash" id="flash-success">
                    <ul>
                        {% for msg in success %}
                            <li class="flash-message" data-type="success"><i class="fa fa-exclamation-triangle"></i>{{ msg }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        {% endwith %}

        {% with errors = get_flashed_messages(category_filter=["error"]) %}
            {% if errors %}
                <div class="flash" id="flash-error">
                    <ul>
                        {% for msg in errors %}
                            <li class="error-message" data-type="error"><i class="fa fa-exclamation-triangle"></i>{{ msg }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        {% endwith %}
    </header>
    
    <main>
        <section class="content">
            <div class="container">
                <section class="profile"> 
                    <article class="doctor-card">
                        <section class="left">
                            <img src="{{ url_for('static', filename='images/doctor.jfif') }}" height="100" width="100" alt="Profile picture of doctor">
                        </section>

                        <section class="right">
                            <div class="name">
                                <h3>{{ doctors.firstname }} {{ doctors.lastname }}</h3>
                                <p>{{ doctors.type }}</p>
                            </div>

                            <div class="rating">
                                <div class="rate">
                                    <p style="margin-right: 5px;">4.6</p>
                                    <i class="fa fa-star"></i>
                                </div>

                                <div class="rate-count">
                                    <p>14 ratings</p>
                                </div>
                            </div>

                            <div class="speciality">
                                <p>Dentistry</p>
                                <p>Surgery</p>
                                <p>Implantology</p>
                                <p>Paediatric</p>
                                <p>Surgery</p>
                            </div>
                        </section>
                    </article>
                </section>
                
                <section class="info">    
                    <div id="about">
                        <div class="label-data">
                            <div class="label-data-item">
                                <i class="fa fa-user"></i>
                                <span>
                                    <h2>1.2 K</h2>
                                    <h4>Patients</h4>
                                </span>
                            </div>

                            <div class="label-data-item">
                                <i class="fa fa-hourglass"></i>
                                <span>
                                    <h2>9 Years</h2>
                                    <h4>Experience</h4>
                                </span>
                            </div>
                        </div>
                    </div>
                    
                    <div id="time">
                        <div class="label-data">
                            <div class="label-data-item">
                                <h4>Mon - Fri</h4>
                                <h4>08:00 AM - 09:00 PM</h4>
                            </div>

                            <div class="label-data-item">
                                <address>
                                    <i class="fa fa-phone"><a href="tel:+91 {{ doctors.phone | int }}"><h4>+91 {{ doctors.phone | int }}</h4></a></i>
                                </address>
                            </div>
                        </div>
                    </div>
              
                    <div id="address">
                        <div class="label-data">
                            <div class="label-data-item">
                                <i class="fa fa-map-pin"></i>
                                <address>
                                    <h4>Swami Satyanand Maharaj Road, near Maxus Mall, Bhayandar West, Mira Bhayandar, Maharashtra 401101</h4>
                                    <a style="color: var(--error);" target="_blank"
                                       href="https://www.google.com/maps/place/Tembha+Hospital/@19.2979695,72.8345816,15z/data=!4m5!3m4!1s0x3be7b1cc51ce7343:0x95e7e3b76ab73392!8m2!3d19.2974719!4d72.8481172">
                                       <u>View on maps</u>
                                    </a>
                                </address>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </section>
        
        <!-- Book appointment button -->
        <div class="book-button-container">
            <div class="book-button">
                <a href="{{ url_for('doctors.doctor_appointment', doctor_id=doctors.id) }}">Book Appointment</a>
            </div>
        </div>
    </main>
    
    {{ dummyNav() }}
    {{ footer("footer-item", "footer-item", "footer-item") }}

    <script type = "text/javascript" src = "{{ url_for('static', filename = 'js/essentials.js') }}"></script>
    <script type = "text/javascript" src = "{{ url_for('static', filename = 'js/nav.js') }}"></script>
</body>
</html>